name: MaskeAntiKufur
main: org.oyuncozucu.maskeAntiKufur.MaskeAntiKufurPlugin
version: 1.0.0
api-version: 1.21
website: https://maske.network/


commands:
  antikufur:
    description: ANTİ KÜFÜRDEN NE BEKLİYORSUN DAYI
    usage: /antikufur [reload|status]
    permission: antikufur.admin

  permissions:
    antikufur:
      description: Anti küfür plugin izni
      default: op
      antikufur.bypass:
        description: küfür kontrolünü atlama izni
        default: false
