settings:
  detection_mode: "contains"
  case_sensitive: false
  messages:
    warning: "[MaskeAntiKüfür ] DADİ DADİ POLİS EMRE GELDİ!!!! KÜFÜR YASAK {player} adlı oyuncu uyarıldı :)"
    blocked: "[MaskeAntiKüfür]  sunucuda küfür kullandığın için mesaj engellendi :)"
    admin_notify: "[MaskeAntiKüfür] {player} adlı oyuncu küfür kullandı dediği ise şuydu : {message}"
  website:
    enabled: true
  bad_words:
  - a.m.k
  - amq
  - aq
  - a.q
  - ananı sikim
  - ananı sikeyim
  - anan
  - ananızı
  - ananı
  - anasını
  - orospu
  - orospu çocuğu
  - oç
  - o.c
  - oc
  - piç
  - p*ç
  - p i ç
  - amcık
  - amcigi
  - sikim
  - s i k i m
  - s*kim
  - sikiş
  - s.k.m
  - skm
  - s*k*m
  - s*kiş
  - sikecem
  - s*kecem
  - s.kecem
  - porno
  - fucking
  - fuck
  - your mom
  - fuck your mom
  - allahsız
  - allaha küfür
  - allahı s.k
  - allahı sik
  - allahı s*k
  - tanrıya küfür
  - tanrıyı s.k
  - tanrıyı sik
  - oe
warnings:
  max_warnings: 3
  mute_duration: 300
  messages:
    first: "&c[polis emre] &e uyarı küfür etmeyin"
logging:
  enabled: true
  file: "logs/anti-kufur.log"
